# Fichier emprunté au groupe de Robin Cuénoud :D

dist: bionic

os:
  - linux

language: cpp

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

after_script:
        - cmake --build . --target GEN_RefactorC
