# Fichier emprunté au groupe de Robin Cuénoud :D

dist: bionic

os:
  - linux

language: cpp

before_script:
  - mkdir build
  - cmake

script:
  - cmake --build

after_script:
  - cmake --build --target test_lab
